import Foundation

struct IngredientNormalizer {

    // MARK: - Normalization Map
    // Maps specific ingredient names to their normalized family name
    // Used for recipe matching so "Jasmine Rice" matches recipes calling for "rice"
    // Broth types are kept SPECIFIC — chicken broth ≠ beef broth
    // "pepper" alone → "black pepper"
    static let normalizationMap: [String: String] = [

        // ── RICE ──────────────────────────────────────────────────────────
        "jasmine rice": "rice",
        "basmati rice": "rice",
        "brown rice": "rice",
        "white rice": "rice",
        "wild rice": "rice",
        "arborio rice": "rice",
        "long grain rice": "rice",
        "short grain rice": "rice",
        "sushi rice": "rice",
        "instant rice": "rice",
        "minute rice": "rice",
        "converted rice": "rice",
        "parboiled rice": "rice",
        "black rice": "rice",
        "red rice": "rice",
        "forbidden rice": "rice",
        "carnaroli rice": "rice",
        "valencia rice": "rice",

        // ── PASTA (each shape stays distinct — spaghetti ≠ penne ≠ rigatoni) ────
        // Only true synonyms (same shape, different spelling/name) are grouped.
        "linguini": "linguine",           // spelling variant
        "fettuccini": "fettuccine",       // spelling variant
        "tagliatelle": "fettuccine",      // nearly identical ribbon noodle
        "bow tie pasta": "farfalle",      // same shape, common alias
        "butterfly pasta": "farfalle",    // same shape, common alias
        "angel hair": "capellini",        // same shape, common alias
        "elbow macaroni": "macaroni",     // same shape, common alias
        "elbow pasta": "macaroni",        // same shape, common alias
        "mezze penne": "penne",           // smaller penne — close enough
        "pennette": "penne",              // smaller penne — close enough
        "rotini": "fusilli",              // nearly identical spiral
        "cavatappi": "fusilli",           // spiral variant
        "shells pasta": "shells",         // normalize with/without "pasta"
        "conchiglie": "shells",           // Italian name for shells
        "wide egg noodles": "egg noodles",// width variant, same product category
        "extra wide egg noodles": "egg noodles",
        "lasagna sheets": "lasagna noodles",
        "whole wheat pasta": "pasta",     // dietary variants → generic (no specific shape)
        "gluten free pasta": "pasta",
        "chickpea pasta": "pasta",
        "lentil pasta": "pasta",
        "rice pasta": "pasta",

        // ── NOODLES ───────────────────────────────────────────────────────
        "rice noodles": "rice noodles",
        "flat rice noodles": "rice noodles",
        "pad thai noodles": "rice noodles",
        "rice vermicelli": "rice noodles",
        "glass noodles": "glass noodles",
        "cellophane noodles": "glass noodles",
        "mung bean noodles": "glass noodles",
        "sweet potato noodles": "glass noodles",
        "udon noodles": "udon",
        "udon": "udon",
        "soba noodles": "soba",
        "soba": "soba",
        "ramen noodles": "ramen noodles",
        "instant ramen": "ramen noodles",
        "chow mein noodles": "chow mein noodles",
        "lo mein noodles": "lo mein noodles",
        "wonton noodles": "wonton noodles",
        "spaghetti squash": "spaghetti squash",

        // ── OILS ─────────────────────────────────────────────────────────
        "olive oil": "oil",
        "extra virgin olive oil": "oil",
        "light olive oil": "oil",
        "pure olive oil": "oil",
        "vegetable oil": "oil",
        "canola oil": "oil",
        "coconut oil": "oil",
        "avocado oil": "oil",
        "sunflower oil": "oil",
        "corn oil": "oil",
        "sesame oil": "oil",
        "toasted sesame oil": "oil",
        "peanut oil": "oil",
        "grapeseed oil": "oil",
        "safflower oil": "oil",
        "walnut oil": "oil",
        "truffle oil": "oil",
        "chili oil": "oil",
        "infused olive oil": "oil",
        "cooking spray": "oil",
        "nonstick spray": "oil",

        // ── VINEGAR ───────────────────────────────────────────────────────
        "apple cider vinegar": "vinegar",
        "white vinegar": "vinegar",
        "distilled white vinegar": "vinegar",
        "red wine vinegar": "vinegar",
        "white wine vinegar": "vinegar",
        "rice vinegar": "vinegar",
        "unseasoned rice vinegar": "vinegar",
        "seasoned rice vinegar": "vinegar",
        "balsamic vinegar": "vinegar",
        "balsamic glaze": "balsamic glaze",
        "balsamic reduction": "balsamic glaze",
        "sherry vinegar": "vinegar",
        "champagne vinegar": "vinegar",
        "malt vinegar": "vinegar",
        "coconut vinegar": "vinegar",

        // ── CHICKEN ───────────────────────────────────────────────────────
        "chicken breast": "chicken",
        "chicken breasts": "chicken",
        "boneless skinless chicken breast": "chicken",
        "chicken thigh": "chicken",
        "chicken thighs": "chicken",
        "boneless chicken thighs": "chicken",
        "bone-in chicken thighs": "chicken",
        "chicken drumstick": "chicken",
        "chicken drumsticks": "chicken",
        "chicken leg": "chicken",
        "chicken legs": "chicken",
        "chicken wing": "chicken",
        "chicken wings": "chicken",
        "whole chicken": "chicken",
        "rotisserie chicken": "chicken",
        "ground chicken": "chicken",
        "minced chicken": "chicken",
        "chicken tender": "chicken",
        "chicken tenders": "chicken",
        "chicken cutlet": "chicken",
        "chicken cutlets": "chicken",
        "chicken strip": "chicken",
        "chicken fillet": "chicken",
        "chicken fillets": "chicken",
        "boneless chicken": "chicken",
        "skinless chicken": "chicken",
        "poached chicken": "chicken",
        "shredded chicken": "chicken",
        "cooked chicken": "chicken",
        "leftover chicken": "chicken",

        // ── TURKEY ────────────────────────────────────────────────────────
        "turkey breast": "turkey",
        "turkey thigh": "turkey",
        "turkey leg": "turkey",
        "turkey wing": "turkey",
        "ground turkey": "turkey",
        "minced turkey": "turkey",
        "whole turkey": "turkey",
        "turkey cutlet": "turkey",
        "turkey meatball": "turkey",
        "turkey sausage": "turkey sausage",

        // ── BEEF ─────────────────────────────────────────────────────────
        "ground beef": "beef",
        "minced beef": "beef",
        "beef mince": "beef",
        "80/20 ground beef": "beef",
        "lean ground beef": "beef",
        "extra lean ground beef": "beef",
        "chuck roast": "beef",
        "beef chuck": "beef",
        "chuck steak": "beef",
        "ribeye": "beef",
        "rib eye": "beef",
        "rib-eye": "beef",
        "ribeye steak": "beef",
        "sirloin": "beef",
        "top sirloin": "beef",
        "bottom sirloin": "beef",
        "sirloin steak": "beef",
        "filet mignon": "beef",
        "beef tenderloin": "beef",
        "tenderloin steak": "beef",
        "t-bone": "beef",
        "t bone steak": "beef",
        "porterhouse": "beef",
        "new york strip": "beef",
        "ny strip": "beef",
        "strip steak": "beef",
        "flank steak": "beef",
        "skirt steak": "beef",
        "hanger steak": "beef",
        "flat iron steak": "beef",
        "denver steak": "beef",
        "tri tip": "beef",
        "tri-tip": "beef",
        "beef brisket": "beef",
        "brisket": "beef",
        "beef short rib": "beef",
        "short ribs": "beef",
        "beef rib": "beef",
        "beef shank": "beef",
        "oxtail": "beef",
        "beef stew meat": "beef",
        "stew beef": "beef",
        "beef cubes": "beef",
        "beef roast": "beef",
        "pot roast": "beef",
        "round roast": "beef",
        "rump roast": "beef",
        "eye of round": "beef",
        "top round": "beef",
        "bottom round": "beef",
        "london broil": "beef",
        "beef liver": "beef",
        "corned beef": "beef",
        "pastrami": "beef",

        // ── PORK ─────────────────────────────────────────────────────────
        "ground pork": "pork",
        "minced pork": "pork",
        "pork chop": "pork",
        "pork chops": "pork",
        "bone-in pork chop": "pork",
        "boneless pork chop": "pork",
        "pork tenderloin": "pork",
        "pork loin": "pork",
        "pork roast": "pork",
        "pork shoulder": "pork",
        "pork butt": "pork",
        "boston butt": "pork",
        "pork belly": "pork",
        "pork ribs": "pork",
        "baby back ribs": "pork",
        "spare ribs": "pork",
        "st louis ribs": "pork",
        "pork leg": "pork",
        "ham hock": "pork",
        "pork knuckle": "pork",
        "pork shank": "pork",
        "pork cutlet": "pork",
        "pulled pork": "pork",
        "carnitas": "pork",
        "ham": "ham",
        "honey ham": "ham",
        "spiral ham": "ham",
        "black forest ham": "ham",
        "deli ham": "ham",
        "prosciutto": "prosciutto",
        "prosciutto di parma": "prosciutto",
        "pancetta": "pancetta",
        "guanciale": "pancetta",
        "lardons": "bacon",
        "bacon": "bacon",
        "canadian bacon": "bacon",
        "back bacon": "bacon",
        "thick cut bacon": "bacon",
        "turkey bacon": "turkey bacon",
        "sausage": "sausage",
        "ground sausage": "sausage",
        "breakfast sausage": "sausage",
        "italian sausage links": "sausage",
        "sausage links": "sausage",
        "sausage patties": "sausage",
        "pork sausage": "sausage",
        "italian sausage": "sausage",
        "sweet italian sausage": "sausage",
        "hot italian sausage": "sausage",
        "chorizo": "chorizo",
        "spanish chorizo": "chorizo",
        "mexican chorizo": "chorizo",
        "andouille": "andouille",
        "bratwurst": "sausage",
        "brat": "sausage",
        "kielbasa": "sausage",
        "hot dog": "hot dog",
        "frankfurter": "hot dog",
        "pepperoni": "pepperoni",
        "salami": "salami",
        "genoa salami": "salami",
        "mortadella": "mortadella",

        // ── LAMB & GAME ───────────────────────────────────────────────────
        "ground lamb": "lamb",
        "minced lamb": "lamb",
        "lamb chop": "lamb",
        "rack of lamb": "lamb",
        "lamb shoulder": "lamb",
        "leg of lamb": "lamb",
        "lamb shank": "lamb",
        "lamb loin": "lamb",
        "lamb cutlet": "lamb",
        "ground venison": "venison",
        "venison steak": "venison",
        "duck breast": "duck",
        "duck leg": "duck",
        "duck confit": "duck",
        "whole duck": "duck",
        "ground bison": "bison",
        "bison burger": "bison",

        // ── SEAFOOD — FISH ────────────────────────────────────────────────
        "salmon fillet": "salmon",
        "salmon fillets": "salmon",
        "atlantic salmon": "salmon",
        "wild salmon": "salmon",
        "sockeye salmon": "salmon",
        "smoked salmon": "smoked salmon",
        "lox": "smoked salmon",
        "gravlax": "smoked salmon",
        "tuna steak": "tuna",
        "ahi tuna": "tuna",
        "yellowfin tuna": "tuna",
        "bluefin tuna": "tuna",
        "tilapia fillet": "tilapia",
        "tilapia fillets": "tilapia",
        "cod fillet": "cod",
        "cod fillets": "cod",
        "halibut fillet": "halibut",
        "halibut steak": "halibut",
        "sea bass fillet": "sea bass",
        "chilean sea bass": "sea bass",
        "striped bass": "sea bass",
        "mahi mahi": "mahi mahi",
        "mahi-mahi": "mahi mahi",
        "swordfish steak": "swordfish",
        "red snapper": "snapper",
        "snapper fillet": "snapper",
        "rainbow trout": "trout",
        "trout fillet": "trout",
        "catfish fillet": "catfish",
        "flounder fillet": "flounder",
        "dover sole": "sole",
        "sole fillet": "sole",
        "mackerel fillet": "mackerel",
        "barramundi fillet": "barramundi",
        "branzino": "branzino",
        "monkfish": "monkfish",
        "grouper fillet": "grouper",
        "pollock fillet": "pollock",
        "haddock fillet": "haddock",
        "whiting fillet": "whiting",
        "white fish": "white fish",
        "whitefish": "white fish",

        // ── SEAFOOD — SHELLFISH ───────────────────────────────────────────
        "shrimp": "shrimp",
        "prawns": "shrimp",
        "tiger prawns": "shrimp",
        "jumbo shrimp": "shrimp",
        "large shrimp": "shrimp",
        "medium shrimp": "shrimp",
        "frozen shrimp": "shrimp",
        "raw shrimp": "shrimp",
        "cooked shrimp": "shrimp",
        "gulf shrimp": "shrimp",
        "scallops": "scallops",
        "bay scallops": "scallops",
        "sea scallops": "scallops",
        "lobster tail": "lobster",
        "whole lobster": "lobster",
        "langoustine": "lobster",
        "king crab legs": "crab",
        "dungeness crab": "crab",
        "blue crab": "crab",
        "snow crab": "crab",
        "crab meat": "crab",
        "imitation crab": "imitation crab",
        "littleneck clams": "clams",
        "manila clams": "clams",
        "clams": "clams",
        "mussels": "mussels",
        "blue mussels": "mussels",
        "oysters": "oysters",
        "squid": "squid",
        "calamari": "squid",
        "octopus": "octopus",

        // ── EGGS ─────────────────────────────────────────────────────────
        "egg": "eggs",
        "eggs": "eggs",
        "large eggs": "eggs",
        "extra large eggs": "eggs",
        "medium eggs": "eggs",
        "small eggs": "eggs",
        "brown eggs": "eggs",
        "white eggs": "eggs",
        "free range eggs": "eggs",
        "organic eggs": "eggs",
        "pasture raised eggs": "eggs",
        "egg whites": "egg whites",
        "egg yolks": "egg yolks",
        "egg yolk": "egg yolks",
        "duck eggs": "eggs",
        "quail eggs": "eggs",

        // ── TOFU & PLANT PROTEIN ──────────────────────────────────────────
        "firm tofu": "tofu",
        "extra firm tofu": "tofu",
        "silken tofu": "tofu",
        "soft tofu": "tofu",
        "medium firm tofu": "tofu",
        "smoked tofu": "tofu",
        "tempeh": "tempeh",
        "seitan": "seitan",
        "paneer": "paneer",
        "halloumi": "halloumi",

        // ── DAIRY — MILK ──────────────────────────────────────────────────
        "whole milk": "milk",
        "2% milk": "milk",
        "1% milk": "milk",
        "skim milk": "milk",
        "nonfat milk": "milk",
        "lowfat milk": "milk",
        "reduced fat milk": "milk",
        "full fat milk": "milk",
        "raw milk": "milk",
        "lactose free milk": "milk",
        "lactaid milk": "milk",
        "oat milk": "oat milk",
        "almond milk": "almond milk",
        "soy milk": "soy milk",
        "cashew milk": "cashew milk",
        "coconut milk beverage": "coconut milk beverage",
        "rice milk": "rice milk",
        "hemp milk": "hemp milk",
        "pea milk": "pea milk",
        "flax milk": "flax milk",
        "macadamia milk": "macadamia milk",

        // ── DAIRY — CREAM ─────────────────────────────────────────────────
        "heavy cream": "heavy cream",
        "heavy whipping cream": "heavy cream",
        "whipping cream": "heavy cream",
        "double cream": "heavy cream",
        "light cream": "light cream",
        "half and half": "half and half",
        "half & half": "half and half",
        "coffee cream": "half and half",
        "table cream": "light cream",
        "single cream": "light cream",
        "sour cream": "sour cream",
        "light sour cream": "sour cream",
        "fat free sour cream": "sour cream",
        "reduced fat sour cream": "sour cream",
        "creme fraiche": "sour cream",
        "clotted cream": "clotted cream",

        // ── DAIRY — BUTTER ────────────────────────────────────────────────
        "butter": "butter",
        "unsalted butter": "butter",
        "salted butter": "butter",
        "european butter": "butter",
        "cultured butter": "butter",
        "grass fed butter": "butter",
        "kerrygold butter": "butter",
        "plugra butter": "butter",
        "ghee": "butter",
        "clarified butter": "butter",
        "vegan butter": "butter",
        "plant butter": "butter",
        "margarine": "butter",
        "earth balance": "butter",

        // ── DAIRY — YOGURT ────────────────────────────────────────────────
        "greek yogurt": "yogurt",
        "plain yogurt": "yogurt",
        "whole milk yogurt": "yogurt",
        "lowfat yogurt": "yogurt",
        "nonfat yogurt": "yogurt",
        "vanilla yogurt": "yogurt",
        "skyr": "yogurt",
        "icelandic yogurt": "yogurt",
        "kefir": "kefir",
        "labneh": "yogurt",
        "coconut yogurt": "yogurt",
        "almond yogurt": "yogurt",
        "soy yogurt": "yogurt",

        // ── DAIRY — BUTTERMILK ────────────────────────────────────────────
        "buttermilk": "buttermilk",
        "cultured buttermilk": "buttermilk",
        "low fat buttermilk": "buttermilk",

        // ── CHEESE — SOFT ─────────────────────────────────────────────────
        "cream cheese": "cream cheese",
        "whipped cream cheese": "cream cheese",
        "neufchatel": "cream cheese",
        "ricotta": "ricotta",
        "whole milk ricotta": "ricotta",
        "part skim ricotta": "ricotta",
        "ricotta cheese": "ricotta",
        "mascarpone": "mascarpone",
        "brie": "brie",
        "camembert": "brie",
        "cottage cheese": "cottage cheese",
        "large curd cottage cheese": "cottage cheese",
        "small curd cottage cheese": "cottage cheese",
        "burrata": "fresh mozzarella",
        "fresh mozzarella": "fresh mozzarella",
        "mozzarella balls": "fresh mozzarella",
        "ciliegine": "fresh mozzarella",
        "bocconcini": "fresh mozzarella",

        // ── CHEESE — SEMI-SOFT ────────────────────────────────────────────
        "mozzarella": "mozzarella",
        "shredded mozzarella": "mozzarella",
        "low moisture mozzarella": "mozzarella",
        "part skim mozzarella": "mozzarella",
        "provolone": "provolone",
        "fontina": "fontina",
        "havarti": "havarti",
        "muenster": "muenster",
        "monterey jack": "monterey jack",
        "colby jack": "colby jack",
        "colby": "colby",
        "pepper jack": "pepper jack",
        "gouda": "gouda",
        "smoked gouda": "gouda",
        "aged gouda": "gouda",
        "edam": "edam",

        // ── CHEESE — SEMI-HARD ────────────────────────────────────────────
        "cheddar": "cheddar",
        "cheddar cheese": "cheddar",
        "sharp cheddar": "cheddar",
        "mild cheddar": "cheddar",
        "white cheddar": "cheddar",
        "yellow cheddar": "cheddar",
        "extra sharp cheddar": "cheddar",
        "aged cheddar": "cheddar",
        "shredded cheddar": "cheddar",
        "swiss": "swiss",
        "swiss cheese": "swiss",
        "gruyere": "gruyere",
        "emmental": "swiss",
        "jarlsberg": "swiss",
        "manchego": "manchego",
        "comte": "comte",

        // ── CHEESE — HARD ─────────────────────────────────────────────────
        "parmesan": "parmesan",
        "parmigiano reggiano": "parmesan",
        "parmigiano": "parmesan",
        "parmesan cheese": "parmesan",
        "grana padano": "parmesan",
        "pecorino": "pecorino",
        "pecorino romano": "pecorino",
        "romano": "pecorino",
        "asiago": "asiago",

        // ── CHEESE — OTHER ────────────────────────────────────────────────
        "feta": "feta",
        "feta cheese": "feta",
        "greek feta": "feta",
        "bulgarian feta": "feta",
        "crumbled feta": "feta",
        "queso fresco": "queso fresco",
        "queso blanco": "queso fresco",
        "cotija": "cotija",
        "panela": "panela",
        "oaxaca cheese": "oaxaca",
        "asadero": "oaxaca",
        "blue cheese": "blue cheese",
        "gorgonzola": "blue cheese",
        "roquefort": "blue cheese",
        "stilton": "blue cheese",
        "danish blue": "blue cheese",
        "american cheese": "american cheese",
        "velveeta": "american cheese",

        // ── PRODUCE — ALLIUMS ─────────────────────────────────────────────
        "yellow onion": "onion",
        "white onion": "onion",
        "red onion": "onion",
        "sweet onion": "onion",
        "vidalia onion": "onion",
        "walla walla onion": "onion",
        "cipollini onion": "onion",
        "pearl onion": "onion",
        "spring onion": "green onion",
        "green onion": "green onion",
        "scallion": "green onion",
        "scallions": "green onion",
        "shallot": "shallot",
        "shallots": "shallot",
        "french shallot": "shallot",
        "banana shallot": "shallot",
        "leek": "leek",
        "leeks": "leek",
        "baby leek": "leek",
        "chive": "chive",
        "chives": "chive",

        // ── PRODUCE — TOMATOES ────────────────────────────────────────────
        "tomato": "tomato",
        "tomatoes": "tomato",
        "cherry tomatoes": "tomato",
        "grape tomatoes": "tomato",
        "roma tomatoes": "tomato",
        "plum tomatoes": "tomato",
        "beefsteak tomatoes": "tomato",
        "heirloom tomatoes": "tomato",
        "vine tomatoes": "tomato",
        "campari tomatoes": "tomato",

        // ── PRODUCE — PEPPERS ─────────────────────────────────────────────
        "bell pepper": "bell pepper",
        "red bell pepper": "bell pepper",
        "green bell pepper": "bell pepper",
        "yellow bell pepper": "bell pepper",
        "orange bell pepper": "bell pepper",
        "mini sweet pepper": "bell pepper",
        "sweet pepper": "bell pepper",
        "jalapeno": "jalapeno",
        "jalapeno pepper": "jalapeno",
        "serrano pepper": "serrano",
        "habanero pepper": "habanero",
        "habanero": "habanero",
        "poblano pepper": "poblano",
        "poblano": "poblano",
        "anaheim pepper": "anaheim",
        "fresno chili": "fresno chili",
        "thai chili": "thai chili",
        "banana pepper": "banana pepper",
        "ghost pepper": "ghost pepper",

        // ── PRODUCE — LEAFY GREENS ────────────────────────────────────────
        "spinach": "spinach",
        "baby spinach": "spinach",
        "kale": "kale",
        "lacinato kale": "kale",
        "curly kale": "kale",
        "swiss chard": "chard",
        "rainbow chard": "chard",
        "collard greens": "collard greens",
        "mustard greens": "mustard greens",
        "arugula": "arugula",
        "rocket": "arugula",
        "watercress": "watercress",
        "endive": "endive",
        "radicchio": "radicchio",
        "mixed greens": "mixed greens",
        "spring mix": "mixed greens",
        "mesclun": "mixed greens",
        "salad mix": "mixed greens",
        "baby arugula": "arugula",
        "baby kale": "kale",
        "microgreens": "microgreens",

        // ── PRODUCE — LETTUCE ─────────────────────────────────────────────
        "romaine lettuce": "lettuce",
        "romaine": "lettuce",
        "iceberg lettuce": "lettuce",
        "iceberg": "lettuce",
        "butter lettuce": "lettuce",
        "boston lettuce": "lettuce",
        "bibb lettuce": "lettuce",
        "green leaf lettuce": "lettuce",
        "red leaf lettuce": "lettuce",
        "oak leaf lettuce": "lettuce",

        // ── PRODUCE — BRASSICAS ───────────────────────────────────────────
        "broccoli": "broccoli",
        "broccoli florets": "broccoli",
        "broccolini": "broccolini",
        "broccoli rabe": "broccoli rabe",
        "rapini": "broccoli rabe",
        "cauliflower": "cauliflower",
        "cauliflower florets": "cauliflower",
        "romanesco": "cauliflower",
        "purple cauliflower": "cauliflower",
        "brussels sprouts": "brussels sprouts",
        "brussels sprout": "brussels sprouts",
        "cabbage": "cabbage",
        "green cabbage": "cabbage",
        "red cabbage": "cabbage",
        "napa cabbage": "napa cabbage",
        "savoy cabbage": "cabbage",
        "bok choy": "bok choy",
        "baby bok choy": "bok choy",
        "pak choi": "bok choy",
        "kohlrabi": "kohlrabi",

        // ── PRODUCE — ROOT VEGETABLES ─────────────────────────────────────
        "carrot": "carrot",
        "carrots": "carrot",
        "baby carrots": "carrot",
        "rainbow carrots": "carrot",
        "parsnip": "parsnip",
        "turnip": "turnip",
        "rutabaga": "rutabaga",
        "swede": "rutabaga",
        "beet": "beet",
        "red beet": "beet",
        "golden beet": "beet",
        "beets": "beet",
        "radish": "radish",
        "daikon": "daikon",
        "watermelon radish": "radish",
        "celery root": "celery root",
        "celeriac": "celery root",
        "sunchoke": "sunchoke",
        "jerusalem artichoke": "sunchoke",
        "jicama": "jicama",

        // ── PRODUCE — POTATOES ────────────────────────────────────────────
        "potato": "potato",
        "potatoes": "potato",
        "russet potato": "potato",
        "russet potatoes": "potato",
        "yukon gold potato": "potato",
        "yukon gold potatoes": "potato",
        "yukon gold": "potato",
        "red potato": "potato",
        "red potatoes": "potato",
        "fingerling potato": "potato",
        "fingerling potatoes": "potato",
        "new potato": "potato",
        "new potatoes": "potato",
        "baby potato": "potato",
        "baby potatoes": "potato",
        "purple potato": "potato",
        "idaho potato": "potato",
        "sweet potato": "sweet potato",
        "sweet potatoes": "sweet potato",
        "garnet yam": "sweet potato",
        "jewel yam": "sweet potato",
        "yam": "sweet potato",
        "yams": "sweet potato",
        "purple sweet potato": "sweet potato",

        // ── PRODUCE — SQUASH ──────────────────────────────────────────────
        "zucchini": "zucchini",
        "courgette": "zucchini",
        "yellow squash": "yellow squash",
        "summer squash": "yellow squash",
        "butternut squash": "butternut squash",
        "acorn squash": "acorn squash",
        "delicata squash": "delicata squash",
        "kabocha squash": "kabocha squash",
        "kabocha": "kabocha squash",
        "pumpkin": "pumpkin",
        "sugar pumpkin": "pumpkin",
        "pie pumpkin": "pumpkin",
        "honeynut squash": "butternut squash",
        "carnival squash": "acorn squash",

        // ── PRODUCE — CUCUMBERS ───────────────────────────────────────────
        "cucumber": "cucumber",
        "english cucumber": "cucumber",
        "persian cucumber": "cucumber",
        "pickling cucumber": "cucumber",
        "kirby cucumber": "cucumber",

        // ── PRODUCE — MUSHROOMS ───────────────────────────────────────────
        "mushroom": "mushroom",
        "mushrooms": "mushroom",
        "cremini mushroom": "mushroom",
        "cremini mushrooms": "mushroom",
        "button mushroom": "mushroom",
        "white mushroom": "mushroom",
        "portobello mushroom": "mushroom",
        "portobello cap": "mushroom",
        "shiitake mushroom": "mushroom",
        "shiitake mushrooms": "mushroom",
        "oyster mushroom": "mushroom",
        "enoki mushroom": "mushroom",
        "maitake mushroom": "mushroom",
        "chanterelle mushroom": "mushroom",
        "king trumpet mushroom": "mushroom",

        // ── PRODUCE — OTHER VEGETABLES ────────────────────────────────────
        "asparagus": "asparagus",
        "celery": "celery",
        "celery stalk": "celery",
        "celery stalks": "celery",
        "artichoke": "artichoke",
        "globe artichoke": "artichoke",
        "fennel": "fennel",
        "fennel bulb": "fennel",
        "corn": "corn",
        "sweet corn": "corn",
        "corn on the cob": "corn",
        "baby corn": "corn",
        "green beans": "green beans",
        "green bean": "green beans",
        "haricot vert": "green beans",
        "french green beans": "green beans",
        "snap peas": "snap peas",
        "snow peas": "snow peas",
        "sugar snap peas": "snap peas",
        "peas": "peas",
        "frozen peas": "peas",
        "okra": "okra",
        "eggplant": "eggplant",
        "aubergine": "eggplant",
        "tomatillo": "tomatillo",
        "avocado": "avocado",
        "hass avocado": "avocado",
        "ripe avocado": "avocado",

        // ── PRODUCE — CITRUS ──────────────────────────────────────────────
        "lemon": "lemon",
        "lemons": "lemon",
        "meyer lemon": "lemon",
        "eureka lemon": "lemon",
        "lime": "lime",
        "limes": "lime",
        "key lime": "lime",
        "persian lime": "lime",
        "orange": "orange",
        "oranges": "orange",
        "navel orange": "orange",
        "blood orange": "orange",
        "cara cara orange": "orange",
        "grapefruit": "grapefruit",
        "ruby red grapefruit": "grapefruit",
        "tangerine": "tangerine",
        "clementine": "clementine",
        "mandarin": "mandarin",
        "satsuma": "mandarin",
        "yuzu": "yuzu",
        "kumquat": "kumquat",
        "pomelo": "pomelo",

        // ── PRODUCE — BERRIES ─────────────────────────────────────────────
        "strawberry": "strawberry",
        "strawberries": "strawberry",
        "blueberry": "blueberry",
        "blueberries": "blueberry",
        "raspberry": "raspberry",
        "raspberries": "raspberry",
        "blackberry": "blackberry",
        "blackberries": "blackberry",
        "cranberry": "cranberry",
        "cranberries": "cranberry",
        "gooseberry": "gooseberry",
        "huckleberry": "huckleberry",

        // ── PRODUCE — STONE FRUIT ─────────────────────────────────────────
        "peach": "peach",
        "peaches": "peach",
        "white peach": "peach",
        "yellow peach": "peach",
        "nectarine": "nectarine",
        "plum": "plum",
        "pluot": "plum",
        "apricot": "apricot",
        "apricots": "apricot",
        "cherry": "cherry",
        "cherries": "cherry",
        "bing cherry": "cherry",
        "rainier cherry": "cherry",

        // ── PRODUCE — TROPICAL ────────────────────────────────────────────
        "mango": "mango",
        "mangoes": "mango",
        "ataulfo mango": "mango",
        "champagne mango": "mango",
        "pineapple": "pineapple",
        "papaya": "papaya",
        "banana": "banana",
        "bananas": "banana",
        "plantain": "plantain",
        "kiwi": "kiwi",
        "golden kiwi": "kiwi",
        "dragon fruit": "dragon fruit",
        "guava": "guava",
        "passion fruit": "passion fruit",
        "starfruit": "starfruit",
        "lychee": "lychee",
        "jackfruit": "jackfruit",

        // ── PRODUCE — MELONS ──────────────────────────────────────────────
        "watermelon": "watermelon",
        "cantaloupe": "cantaloupe",
        "honeydew": "honeydew",
        "casaba melon": "melon",
        "galia melon": "melon",

        // ── PRODUCE — APPLES & PEARS ──────────────────────────────────────
        "apple": "apple",
        "apples": "apple",
        "gala apple": "apple",
        "fuji apple": "apple",
        "honeycrisp apple": "apple",
        "granny smith apple": "apple",
        "pink lady apple": "apple",
        "braeburn apple": "apple",
        "mcintosh apple": "apple",
        "pear": "pear",
        "pears": "pear",
        "bartlett pear": "pear",
        "bosc pear": "pear",
        "anjou pear": "pear",
        "asian pear": "pear",

        // ── PRODUCE — GRAPES & OTHER FRUIT ───────────────────────────────
        "grape": "grape",
        "grapes": "grape",
        "red grapes": "grape",
        "green grapes": "grape",
        "fig": "fig",
        "figs": "fig",
        "black fig": "fig",
        "pomegranate": "pomegranate",
        "persimmon": "persimmon",
        "quince": "quince",

        // ── PANTRY — BROTH (kept SPECIFIC) ───────────────────────────────
        "chicken broth": "chicken broth",
        "chicken stock": "chicken broth",
        "low sodium chicken broth": "chicken broth",
        "reduced sodium chicken broth": "chicken broth",
        "beef broth": "beef broth",
        "beef stock": "beef broth",
        "low sodium beef broth": "beef broth",
        "vegetable broth": "vegetable broth",
        "vegetable stock": "vegetable broth",
        "low sodium vegetable broth": "vegetable broth",
        "bone broth": "bone broth",
        "chicken bone broth": "chicken broth",
        "beef bone broth": "beef broth",
        "fish stock": "fish stock",
        "dashi": "dashi",
        "pork broth": "pork broth",
        "lamb broth": "lamb broth",
        "mushroom broth": "mushroom broth",
        "bouillon cube": "bouillon",
        "chicken bouillon": "chicken broth",
        "beef bouillon": "beef broth",

        // ── PANTRY — CANNED TOMATOES ──────────────────────────────────────
        "canned tomatoes": "canned tomatoes",
        "diced tomatoes": "canned tomatoes",
        "crushed tomatoes": "canned tomatoes",
        "whole canned tomatoes": "canned tomatoes",
        "fire roasted tomatoes": "canned tomatoes",
        "san marzano tomatoes": "canned tomatoes",
        "stewed tomatoes": "canned tomatoes",
        "tomato puree": "tomato sauce",
        "tomato sauce": "tomato sauce",
        "marinara sauce": "marinara",
        "pasta sauce": "marinara",
        "arrabiata sauce": "marinara",
        "tomato paste": "tomato paste",

        // ── PANTRY — BEANS (kept SPECIFIC) ───────────────────────────────
        "black beans": "black beans",
        "canned black beans": "black beans",
        "kidney beans": "kidney beans",
        "red kidney beans": "kidney beans",
        "pinto beans": "pinto beans",
        "white beans": "white beans",
        "cannellini beans": "white beans",
        "great northern beans": "white beans",
        "navy beans": "navy beans",
        "chickpeas": "chickpeas",
        "garbanzo beans": "chickpeas",
        "canned chickpeas": "chickpeas",
        "lentils": "lentils",
        "red lentils": "lentils",
        "green lentils": "lentils",
        "brown lentils": "lentils",
        "french lentils": "lentils",
        "lima beans": "lima beans",
        "butter beans": "lima beans",
        "black eyed peas": "black eyed peas",
        "edamame": "edamame",
        "frozen edamame": "edamame",
        "refried beans": "refried beans",
        "baked beans": "baked beans",

        // ── PANTRY — CONDIMENTS ───────────────────────────────────────────
        "soy sauce": "soy sauce",
        "low sodium soy sauce": "soy sauce",
        "dark soy sauce": "soy sauce",
        "light soy sauce": "soy sauce",
        "tamari": "soy sauce",
        "gluten free soy sauce": "soy sauce",
        "coconut aminos": "soy sauce",
        "liquid aminos": "soy sauce",
        "fish sauce": "fish sauce",
        "oyster sauce": "oyster sauce",
        "hoisin sauce": "hoisin sauce",
        "hoisin": "hoisin sauce",
        "worcestershire sauce": "worcestershire sauce",
        "worcestershire": "worcestershire sauce",
        "hot sauce": "hot sauce",
        "sriracha": "sriracha",
        "tabasco": "hot sauce",
        "buffalo sauce": "hot sauce",
        "chili sauce": "chili sauce",
        "sweet chili sauce": "sweet chili sauce",
        "sambal oelek": "sambal oelek",
        "gochujang": "gochujang",
        "miso paste": "miso paste",
        "white miso": "miso paste",
        "red miso": "miso paste",
        "bbq sauce": "bbq sauce",
        "barbecue sauce": "bbq sauce",
        "ketchup": "ketchup",
        "yellow mustard": "mustard",
        "dijon mustard": "mustard",
        "whole grain mustard": "mustard",
        "honey mustard": "mustard",
        "mustard": "mustard",
        "mayo": "mayonnaise",
        "mayonnaise": "mayonnaise",
        "miracle whip": "mayonnaise",
        "caesar dressing": "caesar dressing",
        "ranch dressing": "ranch dressing",
        "italian dressing": "italian dressing",
        "balsamic dressing": "balsamic dressing",
        "teriyaki sauce": "teriyaki sauce",
        "ponzu sauce": "ponzu sauce",
        "ponzu": "ponzu sauce",
        "mirin": "mirin",
        "rice wine": "rice wine",
        "cooking sherry": "sherry",
        "sherry": "sherry",
        "white wine for cooking": "white wine",
        "red wine for cooking": "red wine",
        "enchilada sauce": "enchilada sauce",
        "salsa": "salsa",
        "pico de gallo": "salsa",
        "taco sauce": "taco sauce",

        // ── PANTRY — COCONUT ──────────────────────────────────────────────
        "coconut milk": "coconut milk",
        "full fat coconut milk": "coconut milk",
        "lite coconut milk": "coconut milk",
        "light coconut milk": "coconut milk",
        "coconut cream": "coconut cream",

        // ── PANTRY — NUT BUTTERS ──────────────────────────────────────────
        "peanut butter": "peanut butter",
        "creamy peanut butter": "peanut butter",
        "crunchy peanut butter": "peanut butter",
        "almond butter": "almond butter",
        "cashew butter": "cashew butter",
        "sunflower butter": "sunflower butter",
        "tahini": "tahini",
        "sesame paste": "tahini",

        // ── PANTRY — SWEETENERS ───────────────────────────────────────────
        "honey": "honey",
        "raw honey": "honey",
        "maple syrup": "maple syrup",
        "pure maple syrup": "maple syrup",
        "agave nectar": "agave",
        "agave": "agave",
        "molasses": "molasses",
        "blackstrap molasses": "molasses",
        "corn syrup": "corn syrup",
        "light corn syrup": "corn syrup",
        "dark corn syrup": "corn syrup",
        "golden syrup": "golden syrup",
        "simple syrup": "simple syrup",

        // ── PANTRY — FLOUR ────────────────────────────────────────────────
        "flour": "flour",
        "all purpose flour": "flour",
        "all-purpose flour": "flour",
        "bread flour": "flour",
        "whole wheat flour": "flour",
        "cake flour": "flour",
        "pastry flour": "flour",
        "self rising flour": "flour",
        "self-rising flour": "flour",
        "almond flour": "almond flour",
        "coconut flour": "coconut flour",
        "rice flour": "rice flour",
        "chickpea flour": "chickpea flour",
        "oat flour": "oat flour",
        "buckwheat flour": "buckwheat flour",
        "rye flour": "rye flour",
        "spelt flour": "spelt flour",
        "gluten free flour": "flour",
        "semolina": "semolina",
        "cornmeal": "cornmeal",
        "polenta": "cornmeal",
        "grits": "grits",

        // ── PANTRY — SUGAR ────────────────────────────────────────────────
        "sugar": "sugar",
        "white sugar": "sugar",
        "granulated sugar": "sugar",
        "caster sugar": "sugar",
        "raw sugar": "sugar",
        "turbinado sugar": "sugar",
        "demerara sugar": "sugar",
        "coconut sugar": "sugar",
        "brown sugar": "brown sugar",
        "light brown sugar": "brown sugar",
        "dark brown sugar": "brown sugar",
        "packed brown sugar": "brown sugar",
        "powdered sugar": "powdered sugar",
        "confectioners sugar": "powdered sugar",
        "icing sugar": "powdered sugar",
        "stevia": "stevia",
        "monk fruit sweetener": "monk fruit",
        "erythritol": "erythritol",

        // ── PANTRY — BAKING ───────────────────────────────────────────────
        "baking soda": "baking soda",
        "bicarbonate of soda": "baking soda",
        "baking powder": "baking powder",
        "cream of tartar": "cream of tartar",
        "cornstarch": "cornstarch",
        "corn starch": "cornstarch",
        "arrowroot": "arrowroot",
        "tapioca starch": "tapioca starch",
        "potato starch": "potato starch",
        "active dry yeast": "yeast",
        "instant yeast": "yeast",
        "bread yeast": "yeast",
        "rapid rise yeast": "yeast",
        "cocoa powder": "cocoa powder",
        "dutch cocoa powder": "cocoa powder",
        "unsweetened cocoa": "cocoa powder",
        "chocolate chips": "chocolate chips",
        "semi sweet chocolate chips": "chocolate chips",
        "dark chocolate chips": "chocolate chips",
        "white chocolate chips": "white chocolate chips",
        "dark chocolate": "dark chocolate",
        "baking chocolate": "dark chocolate",
        "unsweetened chocolate": "dark chocolate",
        "semisweet chocolate": "dark chocolate",
        "milk chocolate": "milk chocolate",
        "white chocolate": "white chocolate",
        "vanilla bean": "vanilla bean",
        "gelatin": "gelatin",
        "unflavored gelatin": "gelatin",
        "agar agar": "agar agar",
        "pectin": "pectin",

        // ── PANTRY — GRAINS ───────────────────────────────────────────────
        "oats": "oats",
        "rolled oats": "oats",
        "old fashioned oats": "oats",
        "quick oats": "oats",
        "steel cut oats": "steel cut oats",
        "instant oatmeal": "oats",
        "oat bran": "oat bran",
        "quinoa": "quinoa",
        "bulgur": "bulgur",
        "bulgur wheat": "bulgur",
        "farro": "farro",
        "freekeh": "freekeh",
        "barley": "barley",
        "pearl barley": "barley",
        "millet": "millet",
        "amaranth": "amaranth",
        "teff": "teff",
        "couscous": "couscous",
        "israeli couscous": "couscous",
        "pearl couscous": "couscous",

        // ── PANTRY — BREAD ────────────────────────────────────────────────
        "bread": "bread",
        "white bread": "bread",
        "wheat bread": "bread",
        "whole wheat bread": "bread",
        "sourdough bread": "bread",
        "sourdough": "bread",
        "rye bread": "bread",
        "pumpernickel": "bread",
        "brioche": "brioche",
        "challah": "challah",
        "ciabatta": "ciabatta",
        "baguette": "baguette",
        "focaccia": "focaccia",
        "naan": "naan",
        "naan bread": "naan",
        "pita bread": "pita",
        "pita": "pita",
        "flatbread": "flatbread",
        "lavash": "flatbread",
        "flour tortilla": "flour tortilla",
        "corn tortilla": "corn tortilla",
        "tortilla": "tortilla",
        "wrap": "flour tortilla",
        "burger bun": "burger bun",
        "hamburger bun": "burger bun",
        "hot dog bun": "hot dog bun",
        "slider bun": "burger bun",
        "dinner roll": "dinner roll",
        "english muffin": "english muffin",
        "bagel": "bagel",
        "croissant": "croissant",
        "pretzel bun": "pretzel bun",
        "taco shell": "taco shell",
        "hard taco shell": "taco shell",
        "tostada shell": "tostada shell",

        // ── PANTRY — BREADCRUMBS ──────────────────────────────────────────
        "breadcrumbs": "breadcrumbs",
        "bread crumbs": "breadcrumbs",
        "panko": "panko",
        "panko breadcrumbs": "panko",
        "seasoned breadcrumbs": "breadcrumbs",
        "italian breadcrumbs": "breadcrumbs",
        "croutons": "croutons",

        // ── PANTRY — CRACKERS & SNACKS ────────────────────────────────────
        "graham crackers": "graham crackers",
        "saltine crackers": "crackers",
        "ritz crackers": "crackers",
        "tortilla chips": "tortilla chips",
        "corn chips": "tortilla chips",
        "potato chips": "potato chips",
        "pretzels": "pretzels",
        "popcorn": "popcorn",

        // ── PANTRY — NUTS & SEEDS ─────────────────────────────────────────
        "almonds": "almonds",
        "sliced almonds": "almonds",
        "slivered almonds": "almonds",
        "whole almonds": "almonds",
        "walnuts": "walnuts",
        "walnut halves": "walnuts",
        "pecans": "pecans",
        "pecan halves": "pecans",
        "cashews": "cashews",
        "raw cashews": "cashews",
        "roasted cashews": "cashews",
        "pistachios": "pistachios",
        "peanuts": "peanuts",
        "roasted peanuts": "peanuts",
        "macadamia nuts": "macadamia nuts",
        "brazil nuts": "brazil nuts",
        "hazelnuts": "hazelnuts",
        "filberts": "hazelnuts",
        "pine nuts": "pine nuts",
        "pignoli": "pine nuts",
        "chestnuts": "chestnuts",
        "mixed nuts": "mixed nuts",
        "sunflower seeds": "sunflower seeds",
        "pumpkin seeds": "pumpkin seeds",
        "pepitas": "pumpkin seeds",
        "flaxseed": "flaxseed",
        "ground flaxseed": "flaxseed",
        "chia seeds": "chia seeds",
        "hemp seeds": "hemp seeds",
        "hemp hearts": "hemp seeds",
        "sesame seeds": "sesame seeds",

        // ── PANTRY — DRIED FRUIT ──────────────────────────────────────────
        "raisins": "raisins",
        "golden raisins": "raisins",
        "sultanas": "raisins",
        "dried cranberries": "dried cranberries",
        "craisins": "dried cranberries",
        "dried cherries": "dried cherries",
        "dried apricots": "dried apricots",
        "medjool dates": "dates",
        "dates": "dates",
        "prunes": "prunes",
        "dried plums": "prunes",
        "dried figs": "dried figs",
        "currants": "currants",
        "dried blueberries": "dried blueberries",
        "dried mango": "dried mango",

        // ── PANTRY — CANNED FISH ──────────────────────────────────────────
        "canned tuna": "canned tuna",
        "tuna in water": "canned tuna",
        "albacore tuna": "canned tuna",
        "canned salmon": "canned salmon",
        "canned sardines": "sardines",
        "sardines in oil": "sardines",
        "canned anchovies": "anchovies",
        "anchovy fillets": "anchovies",
        "canned clams": "canned clams",

        // ── PANTRY — PASTA WRAPPERS ───────────────────────────────────────
        "wonton wrappers": "wonton wrappers",
        "dumpling wrappers": "dumpling wrappers",
        "gyoza wrappers": "dumpling wrappers",
        "spring roll wrappers": "spring roll wrappers",
        "rice paper wrappers": "rice paper",
        "phyllo dough": "phyllo dough",
        "filo dough": "phyllo dough",
        "puff pastry": "puff pastry",
        "pie crust": "pie crust",
        "pizza dough": "pizza dough",

        // ── PANTRY — DRIED MUSHROOMS ──────────────────────────────────────
        "dried porcini mushrooms": "dried mushrooms",
        "dried shiitake mushrooms": "dried mushrooms",
        "dried mushrooms": "dried mushrooms",

        // ── PANTRY — SPECIALTY ────────────────────────────────────────────
        "nutritional yeast": "nutritional yeast",
        "protein powder": "protein powder",
        "collagen powder": "collagen",

        // ── HERBS & SPICES — SALT ─────────────────────────────────────────
        "salt": "salt",
        "table salt": "salt",
        "kosher salt": "salt",
        "sea salt": "salt",
        "himalayan salt": "salt",
        "himalayan pink salt": "salt",
        "fine salt": "salt",
        "coarse salt": "salt",
        "flaky salt": "salt",
        "maldon salt": "salt",
        "iodized salt": "salt",
        "celery salt": "celery salt",
        "garlic salt": "garlic salt",
        "onion salt": "onion salt",
        "seasoned salt": "seasoned salt",
        "smoked salt": "smoked salt",

        // ── HERBS & SPICES — PEPPER ───────────────────────────────────────
        // "pepper" alone → "black pepper" is the key fix
        "pepper": "black pepper",
        "black pepper": "black pepper",
        "white pepper": "black pepper",
        "ground pepper": "black pepper",
        "cracked pepper": "black pepper",
        "ground black pepper": "black pepper",
        "cracked black pepper": "black pepper",
        "peppercorn": "black pepper",
        "black peppercorns": "black pepper",
        "freshly ground pepper": "black pepper",
        "freshly cracked pepper": "black pepper",
        "red pepper flakes": "red pepper flakes",
        "pepper flakes": "red pepper flakes",      // Spoonacular variant
        "crushed red pepper": "red pepper flakes",
        "red chili flakes": "red pepper flakes",
        "chili flakes": "red pepper flakes",
        "cayenne": "cayenne pepper",
        "cayenne pepper": "cayenne pepper",
        "ground cayenne": "cayenne pepper",
        "szechuan pepper": "szechuan pepper",
        "sichuan pepper": "szechuan pepper",

        // ── HERBS & SPICES — SPICES ───────────────────────────────────────
        "cumin": "cumin",
        "ground cumin": "cumin",
        "cumin seeds": "cumin",
        "whole cumin": "cumin",
        "coriander": "coriander",
        "ground coriander": "coriander",
        "coriander seeds": "coriander",
        "turmeric": "turmeric",
        "ground turmeric": "turmeric",
        "turmeric powder": "turmeric",
        "paprika": "paprika",
        "sweet paprika": "paprika",
        "smoked paprika": "paprika",
        "hot paprika": "paprika",
        "spanish paprika": "paprika",
        "cinnamon": "cinnamon",
        "ground cinnamon": "cinnamon",
        "cinnamon sticks": "cinnamon",
        "nutmeg": "nutmeg",
        "ground nutmeg": "nutmeg",
        "allspice": "allspice",
        "ground allspice": "allspice",
        "cardamom": "cardamom",
        "ground cardamom": "cardamom",
        "green cardamom": "cardamom",
        "cloves": "cloves",
        "ground cloves": "cloves",
        "whole cloves": "cloves",
        "star anise": "star anise",
        "fennel seeds": "fennel seeds",
        "caraway seeds": "caraway seeds",
        "mustard seeds": "mustard seeds",
        "yellow mustard seeds": "mustard seeds",
        "black mustard seeds": "mustard seeds",
        "celery seeds": "celery seeds",
        "poppy seeds": "poppy seeds",
        "saffron": "saffron",
        "sumac": "sumac",
        "fenugreek": "fenugreek",
        "asafoetida": "asafoetida",
        "hing": "asafoetida",
        "mace": "mace",
        "annatto": "annatto",
        "achiote": "annatto",
        "nigella seeds": "nigella seeds",
        "black seeds": "nigella seeds",
        "gochugaru": "gochugaru",
        "korean chili flakes": "gochugaru",

        // ── HERBS & SPICES — BLENDS ───────────────────────────────────────
        "garam masala": "garam masala",
        "curry powder": "curry powder",
        "madras curry powder": "curry powder",
        "tikka masala spice": "tikka masala spice",
        "tandoori masala": "tandoori masala",
        "chaat masala": "chaat masala",
        "taco seasoning": "taco seasoning",
        "fajita seasoning": "fajita seasoning",
        "cajun seasoning": "cajun seasoning",
        "creole seasoning": "creole seasoning",
        "old bay": "old bay",
        "old bay seasoning": "old bay",
        "jerk seasoning": "jerk seasoning",
        "italian seasoning": "italian seasoning",
        "herbs de provence": "herbs de provence",
        "za'atar": "za'atar",
        "ras el hanout": "ras el hanout",
        "five spice": "five spice",
        "chinese five spice": "five spice",
        "baharat": "baharat",
        "berbere": "berbere",
        "ranch seasoning": "ranch seasoning",
        "onion soup mix": "onion soup mix",
        "everything bagel seasoning": "everything bagel seasoning",
        "lemon pepper seasoning": "lemon pepper seasoning",
        "steak seasoning": "steak seasoning",
        "montreal steak seasoning": "steak seasoning",
        "poultry seasoning": "poultry seasoning",
        "seafood seasoning": "seafood seasoning",
        "pumpkin pie spice": "pumpkin pie spice",
        "apple pie spice": "apple pie spice",
        "chili powder": "chili powder",

        // ── HERBS & SPICES — POWDER AROMATICS ────────────────────────────
        "garlic powder": "garlic powder",
        "onion powder": "onion powder",
        "shallot powder": "shallot powder",
        "mushroom powder": "mushroom powder",
        "tomato powder": "tomato powder",
        "wasabi powder": "wasabi powder",

        // ── HERBS & SPICES — DRIED HERBS ─────────────────────────────────
        "dried basil": "basil",
        "dried oregano": "oregano",
        "oregano flakes": "oregano",   // Spoonacular sometimes returns "Oregano Flakes"
        "dried oregano flakes": "oregano",
        "dried thyme": "thyme",
        "dried rosemary": "rosemary",
        "dried parsley": "parsley",
        "dried dill": "dill",
        "dried sage": "sage",
        "dried mint": "mint",
        "dried cilantro": "cilantro",
        "dried chives": "chives",
        "dried tarragon": "tarragon",
        "dried marjoram": "marjoram",
        "dried bay leaves": "bay leaf",
        "bay leaf": "bay leaf",
        "bay leaves": "bay leaf",
        "dried lavender": "lavender",

        // ── HERBS & SPICES — FRESH HERBS ─────────────────────────────────
        "fresh basil": "basil",
        "basil": "basil",
        "basil leaves": "basil",
        "basil sprig": "basil",
        "basil sprigs": "basil",
        "fresh oregano": "oregano",
        "oregano": "oregano",
        "fresh thyme": "thyme",
        "thyme": "thyme",
        "thyme sprigs": "thyme",
        "thyme sprig": "thyme",
        "fresh rosemary": "rosemary",
        "rosemary": "rosemary",
        "rosemary sprigs": "rosemary",
        "rosemary sprig": "rosemary",
        "fresh parsley": "parsley",
        "parsley": "parsley",
        "flat leaf parsley": "parsley",
        "curly parsley": "parsley",
        "parsley sprig": "parsley",
        "parsley sprigs": "parsley",
        "fresh dill": "dill",
        "dill": "dill",
        "dill weed": "dill",
        "fresh sage": "sage",
        "sage": "sage",
        "sage leaves": "sage",
        "fresh mint": "mint",
        "mint": "mint",
        "peppermint": "mint",
        "spearmint": "mint",
        "fresh cilantro": "cilantro",
        "cilantro": "cilantro",
        "coriander leaves": "cilantro",
        "fresh chives": "chives",
        "fresh tarragon": "tarragon",
        "tarragon": "tarragon",
        "fresh marjoram": "marjoram",
        "marjoram": "marjoram",
        "fresh lavender": "lavender",
        "lemongrass": "lemongrass",
        "lemongrass stalks": "lemongrass",
        "kaffir lime leaves": "kaffir lime leaves",
        "makrut lime leaves": "kaffir lime leaves",
        "curry leaves": "curry leaves",
        "epazote": "epazote",
        "shiso leaves": "shiso",
        "perilla": "shiso",

        // ── HERBS & SPICES — FRESH AROMATICS ─────────────────────────────
        "garlic": "garlic",
        "garlic clove": "garlic",
        "garlic cloves": "garlic",
        "fresh garlic": "garlic",
        "minced garlic": "garlic",
        "roasted garlic": "garlic",
        "garlic paste": "garlic",
        "elephant garlic": "garlic",
        "black garlic": "garlic",
        "ginger": "ginger",
        "fresh ginger": "ginger",
        "ginger root": "ginger",
        "minced ginger": "ginger",
        "ginger knob": "ginger",
        "galangal": "galangal",
        "turmeric root": "fresh turmeric",
        "fresh turmeric": "fresh turmeric",
        "horseradish root": "horseradish",
        "fresh horseradish": "horseradish",
        "wasabi root": "wasabi",

        // ── HERBS & SPICES — EXTRACTS ─────────────────────────────────────
        "vanilla extract": "vanilla extract",
        "pure vanilla extract": "vanilla extract",
        "vanilla bean paste": "vanilla extract",
        "almond extract": "almond extract",
        "peppermint extract": "peppermint extract",
        "lemon extract": "lemon extract",
        "orange extract": "orange extract",
        "coconut extract": "coconut extract",
        "rum extract": "rum extract"
    ]

    // MARK: - Normalize
    static func normalize(_ ingredientName: String) -> String {
        let lowercased = ingredientName.lowercased().trimmingCharacters(in: .whitespaces)
        return normalizationMap[lowercased] ?? lowercased
    }

    // MARK: - Normalized Names
    // Returns both original lowercased name AND normalized family name
    // so "Jasmine Rice" matches both "jasmine rice" and "rice" in recipes
    static func normalizedNames(for ingredientName: String) -> [String] {
        let lowercased = ingredientName.lowercased().trimmingCharacters(in: .whitespaces)
        var names = Set<String>()
        names.insert(lowercased)
        if let normalized = normalizationMap[lowercased] {
            names.insert(normalized)
        }
        return Array(names)
    }

    // MARK: - Egg Detection
    /// Returns true when the ingredient is an egg (not eggplant, egg noodles, egg rolls, etc.)
    static func isEggIngredient(_ name: String) -> Bool {
        let lower = name.lowercased()
        guard lower.contains("egg") else { return false }
        let exclusions = ["eggplant", "egg noodle", "egg roll", "egg white", "egg yolk"]
        return !exclusions.contains(where: { lower.contains($0) })
    }

    // MARK: - Strict Exact Matching
    // No partial string contains — only exact normalized name matches
    // "chicken" does NOT match "chicken broth"
    // Uses Set.isDisjoint for strict set-based comparison
    static func matches(_ recipeIngredient: String, against inventoryIngredients: [String]) -> Bool {
        let recipeNames = Set(normalizedNames(for: recipeIngredient))
        let inventoryNames = Set(inventoryIngredients.flatMap { normalizedNames(for: $0) })
        return !recipeNames.isDisjoint(with: inventoryNames)
    }

    // MARK: - Extract Ingredient Name from Recipe Line
    /// Strips leading quantities and units from a free-text ingredient line.
    /// e.g. "2 cups chicken broth" → "chicken broth"
    ///      "1/2 tsp kosher salt"  → "kosher salt"
    ///      "400g ground beef"     → "ground beef"
    static func extractIngredientName(_ line: String) -> String {
        let words = line.trimmingCharacters(in: .whitespaces)
            .components(separatedBy: " ").filter { !$0.isEmpty }
        // Handle "to taste" as a full-line strip (returns "" — callers should skip empty names)
        let trimmed = line.trimmingCharacters(in: .whitespaces).lowercased()
        if trimmed == "to taste" || trimmed == "salt and pepper to taste" { return "" }

        let unitWords = ["cup","cups","tsp","tbsp","oz","lbs","lb","g","kg","pint","quart","gallon",
                         "can","cans","jar","jars","bag","bags","box","boxes","bottle","bottles",
                         "package","packet","ml","l","liters","litres","fl","cloves","clove",
                         "slices","slice","pieces","piece","sprigs","sprig","whole","large",
                         "medium","small","fresh","dried",
                         // vague measures — strip so "handful of cherry tomatoes" → "cherry tomatoes"
                         "handful","handfuls","pinch","pinches","dash","dashes",
                         "splash","splashes","bunch","bunches","head","heads",
                         "stalk","stalks","knob","knobs","stick","sticks",
                         // connector words — strip "a clove of garlic" → "garlic"
                         "a","an","of","to","taste"]
        var start = 0
        for word in words {
            let lower = word.lowercased()
            if Double(word) != nil { start += 1; continue }
            if word.contains("/"), word.split(separator: "/").allSatisfy({ Double($0) != nil }) {
                start += 1; continue
            }
            if word.first?.isNumber == true && word.contains(where: { $0.isLetter }) {
                start += 1; continue
            }
            if unitWords.contains(lower) { start += 1; continue }
            break
        }
        return words.dropFirst(start).joined(separator: " ")
    }
}
